---
- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: latest
    use: pacman
  become: true

- name: Change user shell
  ansible.builtin.user:
    name: "{{ ansible_env['USER'] }}"
    shell: /bin/zsh
  become: true

- name: Install autosuggestions
  ansible.builtin.package:
    name: zsh-autosuggestions
    state: latest
    use: pacman
  become: true

- name: Install syntax highlighting
  ansible.builtin.package:
    name: zsh-syntax-highlighting
    state: latest
    use: pacman
  become: true

- name: Install completions
  ansible.builtin.package:
    name: zsh-completions
    state: latest
    use: pacman
  become: true

- name: Copy aliases
  ansible.builtin.copy:
    src: "aliases.zsh"
    dest: "{{ ansible_user_dir }}/.zsh/"

- name: Copy public envvars
  ansible.builtin.template:
    src: "envvars_public.j2"
    dest: "{{ ansible_user_dir }}/.zsh/envvars_public.zsh"
  when: envvars_public is defined

- name: Copy private envvars
  ansible.builtin.template:
    src: "envvars_private.j2"
    dest: "{{ ansible_user_dir }}/.zsh/envvars_private.zsh"
  when: envvars_private is defined

- name: Copy zshrc
  ansible.builtin.copy:
    src: ".zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
