---
- name: Install kubectl
  ansible.builtin.package:
    name: kubectl
    state: latest
    use: pacman
  become: true

- name: Create folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.kube"
    state: directory

- name: Set kubeconfig
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.kube/config"
    content: "{{ kubeconfig }}"
    mode: "600"
  when: kubeconfig is defined
