---
- name: Install i3
  ansible.builtin.package:
    name: i3-wm
    state: latest
    use: pacman
  become: true

- name: Copy config
  ansible.builtin.copy:
    src: "config"
    dest: "{{ ansible_user_dir }}/.config/i3/"
