---
- name: Install starship
  ansible.builtin.package:
    name: starship
    state: latest
    use: pacman
  become: true

- name: Create folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/starship"
    state: directory

- name: Copy config
  ansible.builtin.copy:
    src: "config.toml"
    dest: "{{ ansible_user_dir }}/.config/starship/config.toml"
